### PR TITLE
Add slate.rb

### PR DESCRIPTION
**Pull request by chrisberthe**
Adds Shopify's NPM [Slate](https://github.com/Shopify/slate-cli) package.

For review @burke @airhorns @stefanmb @bouk @casperisfine @NathanPJF

### CODE REVIEW

**Comment by chrisberthe** [comment]
Anyone know where this error is coming from?

image

**Comment by chrisberthe** [comment]
Opened an issue: https://github.com/Homebrew/homebrew-core/issues/15013

**Comment by chrmoritz** [comment]
This is an upstream issue with homebrew's `language/node` and will be fixed once https://github.com/Homebrew/brew/pull/2826 gets merged and released in a `brew` version.

As a workaround for now you could add an inreplace at the beginning of install, which removes the prepublish script from the package.json.

**Comment by chrisberthe** [comment]
Awesome, thanks for the quick reply 👍.

**Pull request merged**
