### PR TITLE
Add bottles for Sierra, removing ElCap bottles in most cases.

### PR DESCRIPTION
**Pull request by burke**
@Shopify/dev-infra FYI. The process to build these is:

```bash
brew install --build-bottle libzookeeper
brew bottle libzookeeper
s3cmd put libzookeeper*tar.gz s3://whatever/<same filename>
```

I'm using my own s3 bucket here because it's write-once and checksum-verified so it doesn't really matter. You can use whatever bucket and just change the root_url if you ever need to push one.

@boourns because that old libgraphqlparser version is still in here. I added a sierra bottle to it ¯\\\_(ツ)\_/¯

### CODE REVIEW

**Comment by burke** [comment]
cc also @csfrancis because of luajit-shopify

**Comment by csfrancis** [comment]
Does this mean I can't use bottles on El Capitan anymore?

**Comment by burke** [comment]
It just means it'll compile it from scratch if you do a new install on El Capitan. I'd imagine there won't be a lot of that happening anymore since we're encouraging people to upgrade and fresh environments will be Sierra.

But feel free to paste the old bottle paragraph into that recipe if it's still important to you.

**Comment by csfrancis** [comment]
Nah, it's not that important - I just wanted to know.

**Pull request merged**
