### PR TITLE
nginx: compile with debug

### PR DESCRIPTION
**Pull request by Sirupsen**
plz @es @csfrancis

### CODE REVIEW

**Comment by csfrancis** [comment]
Maybe make this an [option](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Formula-Cookbook.md#adding-optional-steps)?

**Comment by Sirupsen** [comment]
@csfrancis why make it optional? It doesn't log unless you set the debugging level to `debug` anyway

**Comment by csfrancis** [comment]
Yeah, I guess performance doesn't really matter. 🚢

**Comment by es** [comment]
👍

**Pull request merged**
