### PR TITLE
Update ejson to 1.1.0

### PR DESCRIPTION
**Pull request by etiennebarrie**
We will need to upload the new version on your s3, or maybe switch to some Shopify S3 bucket?
Also not sure if we need a Sierra bottle as well.

### CODE REVIEW

**Comment by etiennebarrie** [comment]
How come we didn't get the same result? I used `brew install shopify/shopify/ejson --build-bottle` using go 1.9.2. Shouldn't we get a reproducible build?

**Comment by burke** [comment]
I don't believe they're reproducible, but not sure why in this case.

**Comment by burke** [comment]
probably something to do with mtimes or something

**Comment by etiennebarrie** [comment]
```
$ brew reinstall ejson
==> Reinstalling shopify/shopify/ejson 
==> Downloading https://s3.amazonaws.com/burkelibbey/ejson-1.1.0.high_sierra.bottle.tar.gz
######################################################################## 100,0%
==> Pouring ejson-1.1.0.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/ejson/1.1.0: 11 files, 4.0MB
$ ejson --version
ejson version 1.0.0
```
😬 

But it seems like the problem is in the tarball. 👍

**Comment by burke** [comment]
oh hm. trying again...

**Comment by burke** [comment]
pushed a fix to master.

**Comment by etiennebarrie** [comment]
I think the issue was that https://github.com/Shopify/ejson/tree/1.1.0 does not include https://github.com/Shopify/ejson/commit/b6a32695adb46367bb7945836c38cb4a81d10ffe. I don't see how you could really fix this without shipping a new version of ejson, because https://github.com/Shopify/ejson/archive/1.1.0.tar.gz has the bad version, so building from source would result in a different result than using the bottle.
In any case I still get `1.0.0` after re-installing. 😬 Not sure it's a big deal though.

**Comment by burke** [comment]
I'll take a look tomorrow and fix the release, or make a 1.1.1

**Pull request merged**
