### PR TITLE
Hackdays - build GraphicsMagick with webp support

### PR DESCRIPTION
**Pull request by mkcny**
build GraphicsMagick `--with-webp=yes`

See also https://github.com/Shopify/imagery3/pull/412

cc @nwtn @djoume

### CODE REVIEW

**Comment by nwtn** [comment]
now that @djoume’s GM build (https://github.com/Shopify/graphicsmagick-build/pull/6) merged, we should be able to merge this, right?

cc @mutemule @csfrancis @Thibaut

**Comment by mutemule** [comment]
Sure!

**Comment by mkcny** [comment]
@burke Maybe you'd like to update the bottled version for this?

**Comment by nwtn** [comment]
can somebody 🎩  installing this and then doing `gm -version` and checking that webp worked properly?

```
Feature Support:
  Native Thread Safe       yes
  …
  WebP                     yes
  …
  ZLIB                     yes
```

i'm getting inconsistent results between my machine and another dev’s. wondering if we need to explicitly make sure libwebp is installed first before the build happens.

**Comment by mkcny** [comment]
It looks like `webp` is a runtime dependency. I've updated the formula so `webp` is no longer optional. This fixed `gm -version` indicating no webp support for me.

**Comment by burke** [comment]
```ruby
    revision 3
    sha256 "625cb0e794c282e0724240e4627b63bb92d3ef32ecfdc783ad35e3f323d94278" => :sierra
```
...and remove the elcap line

**Comment by mkcny** [comment]
Thanks, @burke. Updated!

**Comment by mkcny** [comment]
🎩:

```
21:41:07 mike@local:~
$ brew install shopify-graphicsmagick
==> Installing shopify-graphicsmagick from shopify/shopify
==> Installing dependencies for shopify/shopify/shopify-graphicsmagick: webp
==> Installing shopify/shopify/shopify-graphicsmagick dependency: webp
==> Downloading https://homebrew.bintray.com/bottles/webp-0.5.1.sierra.bottle.tar.gz
Already downloaded: /Users/mike/Library/Caches/Homebrew/webp-0.5.1.sierra.bottle.tar.gz
==> Pouring webp-0.5.1.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/webp/0.5.1: 34 files, 1.8M
==> Installing shopify/shopify/shopify-graphicsmagick
==> Downloading http://burkelibbey.s3.amazonaws.com/shopify-graphicsmagick-1.4.020150705_2.sierra.bottle.tar.gz
Already downloaded: /Users/mike/Library/Caches/Homebrew/shopify-graphicsmagick-1.4.020150705_2.sierra.bottle.tar.gz
==> Pouring shopify-graphicsmagick-1.4.020150705_2.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/shopify-graphicsmagick/1.4.020150705_2: 290 files, 10.2M

21:41:11 mike@local:~
$ gm -version
GraphicsMagick 1.4 snapshot-20150705 Q16 http://www.GraphicsMagick.org/
Copyright (C) 2002-2014 GraphicsMagick Group.
Additional copyrights and licenses apply to this software.
See http://www.GraphicsMagick.org/www/Copyright.html for details.

Feature Support:
  Native Thread Safe       yes
  Large Files (> 32 bit)   yes
  Large Memory (> 32 bit)  yes
  BZIP                     yes
  DPS                      no
  FlashPix                 no
  FreeType                 yes
  Ghostscript (Library)    no
  JBIG                     no
  JPEG-2000                no
  JPEG                     yes
  Little CMS               no
  Loadable Modules         no
  OpenMP                   no
  PNG                      yes
  TIFF                     yes
  TRIO                     no
  UMEM                     no
  WebP                     yes
  WMF                      no
  X11                      no
  XML                      yes
  ZLIB                     yes

Host type: x86_64-apple-darwin16.1.0

Configured using the command:
  ./configure  '--prefix=/usr/local/Cellar/shopify-graphicsmagick/1.4.020150705_2' '--disable-dependency-tracking' '--enable-shared' '--disable-static' '--disable-openmp' '--with-quantum-depth=16' '--with-webp=yes' '--without-gslib' '--with-gs-font-dir=/usr/local/share/ghostscript/fonts' '--without-x' '--without-lcms2' 'CC=clang' 'CXX=clang++'

Final Build Parameters:
  CC       = clang
  CFLAGS   = -g -O2 -Wall -D_THREAD_SAFE
  CPPFLAGS = -I/usr/local/opt/freetype/include/freetype2 -I/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/libxml2
  CXX      = clang++
  CXXFLAGS = -D_THREAD_SAFE
  LDFLAGS  = -L/usr/local/opt/freetype/lib -L/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/lib
  LIBS     = -lwebp -ltiff -lfreetype -ljpeg -lpng16 -llzma -lbz2 -lxml2 -lz -lm -lpthread
```

**Pull request merged**
