### PR TITLE
Add Voucher Client

### PR DESCRIPTION
**Pull request by catherinejones**
This pull request adds Voucher Client, which works with our [open source Voucher project](https://github.com/shopify/voucher). This change is to enable developers to install Voucher Client through Homebrew instead of having to setup a Go development environment.

### CODE REVIEW

**Comment by lugray** [comment]
I'd suggest taking a look at how https://github.com/Shopify/homebrew-shopify/blob/master/secret-sender.rb is set up to be more idiomatically brew and achieve the same goal.  It'll allow a forced build from source.

**Comment by catherinejones** [comment]
We're currently using Goreleaser to build release versions of Voucher, which [doesn't appear to support those kinds of formula](
https://goreleaser.com/homebrew). Is there a concern regarding building packages this way? I can try to write a more idiomatic formula, but it'll be a lot messier to support setting the version correctly, as that has to be passed to the formula via the ldflags.

**Comment by catherinejones** [comment]
I'm also the author of ejson2env and I've been using the workflow Burke described [here](https://github.com/Shopify/ejson2env/blob/master/CONTRIBUTING.md#releasing) and I was hoping to move away from this.

**Comment by catherinejones** [comment]
Oh! Thank you! :)

**Pull request merged**
