### PR TITLE
Bump lua-nginx-module to 0.10.15

### PR DESCRIPTION
**Pull request by lavoiesl**
Picks up support for openssl@1.1, openssl@1.0 being EOL.

Fixes https://github.com/Shopify/network-foundations/issues/226

### CODE REVIEW

**Comment by lavoiesl** [comment]
Fixes https://github.com/Shopify/network-foundations/issues/226

**Comment by lavoiesl** [comment]
🎩 
```
╰─$ brew install shopify/shopify/nginx-shopify
==> Installing nginx-shopify from shopify/shopify
Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or
https://developer.apple.com/download/more/.

==> Installing dependencies for shopify/shopify/nginx-shopify: lua-nginx-module
==> Installing shopify/shopify/nginx-shopify dependency: lua-nginx-module
==> Downloading https://github.com/openresty/lua-nginx-module/archive/v0.10.15.tar.gz
Already downloaded: /Users/seb/Library/Caches/Homebrew/downloads/2ceb02a04596bd8e5b02bf5dc70fbb3b1a70d64283317b9b8d2a85046a1d38b0--lua-nginx-module-0.10.15.tar.gz
🍺  /usr/local/Cellar/lua-nginx-module/0.10.15: 360 files, 4.5MB, built in 5 seconds
==> Installing shopify/shopify/nginx-shopify
==> Downloading https://nginx.org/download/nginx-1.13.9.tar.gz
Already downloaded: /Users/seb/Library/Caches/Homebrew/downloads/dd4f389509618489f09f07477300703c71228a1655eeb3913dcdf76cde745c7c--nginx-1.13.9.tar.gz
==> Downloading https://gist.githubusercontent.com/marc-barry/63b7bc9481d73211a895efcb1b98b22e/raw/74f983ca4ab3974f7bcd059de9a6066cf5d3c430/openresty-ssl_cert_cb_yield.patch
Already downloaded: /Users/seb/Library/Caches/Homebrew/downloads/e740ecfd5a4f0e5fc8c37ef8acceda8bf62a099718aec99ec94a6f7a7bd3ea75--openresty-ssl_cert_cb_yield.patch
==> Downloading https://gist.githubusercontent.com/marc-barry/cdf0eba34c02521ae9a3af27158b6ff9/raw/599c35039320b681bf2b64af9061f0dcbf64a8e0/vary_header_length.patch
Already downloaded: /Users/seb/Library/Caches/Homebrew/downloads/81f46b9dd4010f2e183b4ea19b3dd3e750c141d34efbe9e2e24a18c413f00e9f--vary_header_length.patch
==> Patching
==> Applying openresty-ssl_cert_cb_yield.patch
patching file src/event/ngx_event_openssl.c
Hunk #1 succeeded at 1347 (offset 137 lines).
==> Applying vary_header_length.patch
patching file src/http/ngx_http_cache.h
==> ./configure --prefix=/usr/local/Cellar/nginx-shopify/1.13.9 --with-http_ssl_module --with-http_realip_module --with-http_stub_status_module --with-http_geoip_module --with-http_v2_module --with-stream --with-ipv6 --with-pcre --with-de
==> make install
==> Downloading https://github.com/openresty/lua-resty-core/archive/v0.1.12.tar.gz
==> Downloading from https://codeload.github.com/openresty/lua-resty-core/tar.gz/v0.1.12
######################################################################## 100.0%
🍺  /usr/local/Cellar/nginx-shopify/1.13.9: 38 files, 1.7MB, built in 50 seconds
```

However:
```
$ /usr/local/bin/nginx

nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
nginx: [error] lua_load_resty_core failed to load the resty.core module from https://github.com/openresty/lua-resty-core; ensure you are using an OpenResty release from https://openresty.org/en/download.html (rc: 2, reason: module 'resty.core' not found:
	no field package.preload['resty.core']
	no file '../lua-resty-core/lib/resty/core.lua'
	no file '../lua-resty-lrucache/lib/resty/core.lua'
	no file './resty/core.lua'
	no file '/usr/local/Cellar/luajit-shopify/2.1.0-beta2/share/luajit-2.1.0-beta2/resty/core.lua'
	no file '/usr/local/share/lua/5.1/resty/core.lua'
	no file '/usr/local/share/lua/5.1/resty/core/init.lua'
	no file '/usr/local/Cellar/luajit-shopify/2.1.0-beta2/share/lua/5.1/resty/core.lua'
	no file '/usr/local/Cellar/luajit-shopify/2.1.0-beta2/share/lua/5.1/resty/core/init.lua'
	no file './resty/core.so'
	no file '/usr/local/lib/lua/5.1/resty/core.so'
	no file '/usr/local/Cellar/luajit-shopify/2.1.0-beta2/lib/lua/5.1/resty/core.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file './resty.so'
	no file '/usr/local/lib/lua/5.1/resty.so'
	no file '/usr/local/Cellar/luajit-shopify/2.1.0-beta2/lib/lua/5.1/resty.so'
	no file '/usr/local/lib/lua/5.1/loadall.so')
```

Not sure if expected or what the fix is

**Comment by lavoiesl** [comment]
I tried bumping the other dependencies, but still the same error:

```
$ /usr/local/opt/nginx-shopify/bin/nginx
nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
nginx: [error] lua_load_resty_core failed to load the resty.core module from https://github.com/openresty/lua-resty-core; ensure you are using an OpenResty release from https://openresty.org/en/download.html (rc: 2, reason: module 'resty.core' not found:
	no field package.preload['resty.core']
	no file '../lua-resty-core/lib/resty/core.lua'
	no file '../lua-resty-lrucache/lib/resty/core.lua'
	no file './resty/core.lua'
	no file '/usr/local/Cellar/luajit-shopify/2.1.0-beta3/share/luajit-2.1.0-beta3/resty/core.lua'
	no file '/usr/local/share/lua/5.1/resty/core.lua'
	no file '/usr/local/share/lua/5.1/resty/core/init.lua'
	no file '/usr/local/Cellar/luajit-shopify/2.1.0-beta3/share/lua/5.1/resty/core.lua'
	no file '/usr/local/Cellar/luajit-shopify/2.1.0-beta3/share/lua/5.1/resty/core/init.lua'
	no file './resty/core.so'
	no file '/usr/local/lib/lua/5.1/resty/core.so'
	no file '/usr/local/Cellar/luajit-shopify/2.1.0-beta3/lib/lua/5.1/resty/core.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file './resty.so'
	no file '/usr/local/lib/lua/5.1/resty.so'
	no file '/usr/local/Cellar/luajit-shopify/2.1.0-beta3/lib/lua/5.1/resty.so'
	no file '/usr/local/lib/lua/5.1/loadall.so')
nginx: [emerg] bind() to 0.0.0.0:8080 failed (48: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8080 failed (48: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8080 failed (48: Address already in use)
```


What's weird is that the module appears to be there:
```
/usr/local/opt/nginx-shopify/lib/lua/lib/resty/core.lua
```

According to https://github.com/openresty/lua-nginx-module/issues/1533#issuecomment-524082852, we need to add it to the `lua_package_path`

**Comment by lavoiesl** [comment]
Alright 🎉 
By installing the files to `/usr/local/share/lua/5.1`, it's now being picked up and no modification of the lua_package_path is necessary. I think this is the best, because we avoid tempering with use configuration.

🎩 
```
$ /usr/local/Cellar/nginx-shopify/1.13.9/bin/nginx
nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
nginx: [emerg] bind() to 0.0.0.0:8080 failed (48: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8080 failed (48: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8080 failed (48: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8080 failed (48: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8080 failed (48: Address already in use)
nginx: [emerg] still could not bind()
```

**Comment by lavoiesl** [comment]
I’m not sure how to actually test the new nginx + modules though

**Comment by honkfestival** [comment]
@lavoiesl I think running integration tests in https://github.com/Shopify/nginx-routing-modules is what you're looking for.

**Comment by lavoiesl** [comment]
Seems to be working fine on `spy`, it just needs https://github.com/Shopify/spy/pull/6654

My only concern is for https://github.com/Shopify/nginx-routing-modules, which I’m not sure how to test. But I’ll go ahead and merge this. 

If anyone has issues, we can investigate a forward-fix or revert.

It’s currently broken anyway 🤷‍♂

**Pull request merged**
