### PR TITLE
Add imagemagick at old version supported by rmagick

### PR DESCRIPTION
**Pull request by lugray**
Problem seems to be here: https://github.com/ImageMagick/ImageMagick6/commit/e819f52a2a641774cd4f2e9cbfde3d5a1daa8cea where 5->6, this is for 6.9.9-41 release, so based this on the https://github.com/Homebrew/homebrew-core/blob/e9f6bb3a73fa27ba5d30e3346fbc641b1e85e61f/Formula/imagemagick%406.rb 6.9.9-40 formula version.

### CODE REVIEW

**Comment by lugray** [comment]
Works towards fixing Shopify/dev-acceleration#812

**Comment by rafaelfranca** [comment]
What we are going to do to remove the version pin? I don't think it is healthy for the codebase to just lock in a version. We should make sure that we can upgrade in the future.

**Comment by lugray** [comment]
We need someone to maintain https://github.com/rmagick/rmagick. Latest commits are from 2 years ago.  Either that or remove it from all our apps.

**Comment by samdoiron** [comment]
Does the downgrade work for everyone? For me it errors out looking for `livMagickWand-6.Q16.6.dylib` and whe symlinked to that location complains that `RMagick2.bundle requires version 7.0.0 or later`.

**Comment by rafaelfranca** [comment]
Second part https://github.com/Shopify/shopify/pull/155791

**Pull request merged**
